version: "3.7"

services:
  qie:
    image: qvera/qie:latest
    volumes:
      - ./qie_backup:/java/qie/backup:rw
    environment:
      JAVA_OPTIONS: -Xmx4096m
      connection.driver: org.mariadb.jdbc.Driver
      connection.url: jdbc:mariadb://db:3306/qie
      connection.username: root
      connection.password: root
      hibernate.dialect: com.qvera.qie.persistence.MariaDB103UnicodeDialect
      qie.haEngine: EnterpriseHAServiceImpl
    stop_grace_period: 5m
    healthcheck:
      test: curl --fail -s http://localhost/qieStatus || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: "6h"
    depends_on:
      - db
    ports:
      - 8081:80
  db:
    image: mariadb:10.5.1
    volumes:
      - ./mariadb-data:/var/lib/mysql:rw
      - ./mariadb-init:/tmp/database/:rw
    environment:
      MYSQL_DATABASE: qie
      MYSQL_ROOT_PASSWORD: root
    command:
      - --max-allowed-packet=500M
      # This needs to be increased so we can scale QIE to 10 without an issue.
      - --max-connections=1000
      - --init-file=/tmp/database/create_db.sql
    ports:
      # Optional - This is exposed so we can connect via MySQL Workbench
      - 3310:3306
    restart: always
