version: "3.3"

services:
    orthanc:
        image: osimis/orthanc:22.6.1-full
        ports: [8042:8042,5432:5432]
        environment:
            - ORTHANC__AUTHENTICATION_ENABLED=true
            - ORTHANC__DICOM_SERVER_ENABLED=true
            - ORTHANC__NAME="orthanc"
            - ORTHANC__REGISTERED_USERS={"student":"student"}
            - WVB_ENABLED=true
            - ORTHANC__DICOM_CHECK_CALLED_AET=false
        secrets:
            - orthanc.json
secrets:
  orthanc.json:
    file: orthanc.json